### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KishanManani** [simonbromberg/googlefitbit#1]
Hi Simon,
Thanks for the script. On the very last stage when I try to authorize I get the following error:

Error retrieving token: 401 (line 305, file "Service", project "OAuth2")

What should I try to do?

Many thanks,
Kishan

**Comment by simonbromberg** [comment]
Make sure you're using the right OAuth2 credentials from Fitbit. That error is originating in the OAuth2 library, not from my script.

**Comment by KishanManani** [comment]
Thanks for that. Re-did things and it worked.

Thank you very much for the script and making it publicly available. Really appreciate it!

Best,
Kishan
