### ISSUE TITLE
Heartrate.gs OAuth2 Reference Error

### ISSUE THREAD

**Issue by jfclague** [simonbromberg/googlefitbit#10]
When running the Heartrate.gs in Google Script Editor, I get a ReferenceError: "OAuth2" is not defined when running the Authorize/Download Data Fitbit function.

Under the script editor, I get this error message:

![error message](https://cloud.githubusercontent.com/assets/17296285/13113021/55f7c78c-d55b-11e5-8475-01e1847c6881.jpg)

Any help would be greatly appreciated!!!

Thanks,
Jim

**Comment by simonbromberg** [comment]
This error message with the deprecated items is unrelated to the problem you're having. You probably haven't set up the OAuth2 library properly. Make sure you follow the steps provided in the readme.
