### ISSUE TITLE
State token invalid or expired

### ISSUE THREAD

**Issue by rmnygaard** [simonbromberg/googlefitbit#13]
I'm going through the process of loading this code and everything goes as expected until I go to the authorize part. It goes to the fitbit page with 'heart rate', 'activity and exercise', and 'profile' where you can deny or allow. Upon clicking 'allow'. This error appears: 
"The state token is invalid or has expired. Please try again."

**Comment by rmnygaard** [comment]
[fitbit error.pdf](https://github.com/simonbromberg/googlefitbit/files/169738/fitbit.error.pdf)

**Comment by simonbromberg** [comment]
Doesn't look like something specific to this library. 
Have you tried it more than once?

**Comment by rmnygaard** [comment]
I've tried it multiple times on different computers and using different browsers.

**Comment by simonbromberg** [comment]
Verify you have followed the instructions correctly. Possible mistake with the the project key / callback URI

**Comment by rmnygaard** [comment]
I have. I believe the issue isn't with the code. I thought I would be able to run this code for multiple fitbits (for a research study) with one api from fitbit (at least they said I could). Thank you!

**Comment by simonbromberg** [comment]
I have run this for multiple Fitbits for a research study using a single API account, although one needs a different callback URI (ie a different Google sheet, with project key etc) for each Fitbit account. All you have to do is add each of the callback URIs in the box on the Fitbit API management website on a separate line, and each one has its own project key etc.

Originally, before the OAuth2 change, I did manage to get 10 different Fitbit accounts loading data into a single spreadsheet, but after the change I couldn't get it to work. I was nearing the end of the data collection period so I gave up trying to figure it out. Should have been able to change the SERVICE_IDENTIFIER for each Fitbit account (ie. save an array of service identifiers in the sheet properties, or say use fitbit_# with # from 1 to 10), but couldn't get it to work. If you try it out let me know how it goes.
