### ISSUE TITLE
heartrate.gs: Incorrect range height, was 0 but should be 2

### ISSUE THREAD

**Issue by roger77** [simonbromberg/googlefitbit#19]
I am able to download data with interday.gs. When I setup and then run the heartrate.gs I get the above error. Any ideas?

**Comment by simonbromberg** [comment]
What line?

**Comment by andymusic** [comment]
![image](https://cloud.githubusercontent.com/assets/25960146/23220623/7a191d3a-f91a-11e6-88d8-e6ab8187e5ff.png)

I have the same issue with the intraday.gs (adapted to get heart rate). Hope the screenshot is helpful?

**Comment by simonbromberg** [comment]
Please go into the script and figure out what line it occurs on.

**Comment by andymusic** [comment]
I'm sorry. I don't know how to do that. If you could give me some guidance, I can try.

**Comment by andymusic** [comment]
Got it - I think! Looks like line 320...sorry for my inexperience/ineptitude!

![image](https://cloud.githubusercontent.com/assets/25960146/23221436/00c3de5e-f91d-11e6-906b-ae0c4fe36125.png)

**Comment by simonbromberg** [comment]
Are you sure you have heart rate data in the time range you specified in set up?

I just got the same thing when I was doing a day without data, and it worked fine when I switched to a day with data.

**Comment by simonbromberg** [comment]
I updated the script. It now shows an alert if the heart rate data table is empty and returns before trying to set the data in the spreadsheet.
