### ISSUE TITLE
Error on Authorization

### ISSUE THREAD

**Issue by JozefJarosciak** [simonbromberg/googlefitbit#23]
Everything was working fine until today. Now I get this error when I use the sync option:
![image](https://cloud.githubusercontent.com/assets/3492464/24292285/0bde98b2-1063-11e7-833e-8a48c3bf29c0.png)

And when I try to authorize I get:
Data storage error (line 493, file "Service", project "OAuth2")

Any ideas?

**Comment by simonbromberg** [comment]
What version of the Google Oauth2 library are you using?

**Comment by JozefJarosciak** [comment]
It's working again. Not sure what the problem was, but it resolved itself.
