### ISSUE TITLE
intraday_all for yesterday

### ISSUE THREAD

**Issue by lilmo** [simonbromberg/googlefitbit#27]
Hi!
First of all, THANK YOU very much for publishing these scripts, I wouldn't have been able to create them myself :)

I created a script to generate a new Google spreadsheet everyday with the data provided by intraday_all.gs. For it to work, I would need the intraday_all script to fetch *yesterday*'s data, not today's (else I would have to run my script at exactly 11:59pm every day, and google triggers don't allow to be that precise). I couldn't find what I should change in the code to override the "today" from the setup form.
Any help would be greatly appreciated.
Thanks!

**Comment by dsoiM** [comment]
"yesterday" as a text input should be already supported

**Comment by lilmo** [comment]
Thanks for answering @dsoiM.
Unfortunately I tried to put "yesterday" in the setup form but I get an error (type error [...] "dataset" from undefined).

**Comment by lilmo** [comment]
I found a solution. It's not pretty but it does the trick. I'm sharing it here is case anybody else is interrested.

I modified the refreshTimeSeries function so it receives a parameter to override the one set in the "setup" form.

```
function refreshTimeSeries(date) {
//[...] 
//replaced var dateString = getFirstDate(); by the following

var dateString = null;
      
      if (date != null){
        dateString = date;
      }
      else{
        dateString = getFirstDate();
      }

//[...]
```

And then I call refreshTimeSeries from saveYesterdayInNewSheet, which is executed everyday thanks to a Google Script trigger:
```
function saveYesterdayInNewSheet() {
  
  var yesterdayDate = Utilities.formatDate(subDaysFromDate(new Date(), 1), "GMT", "yyyy-MM-dd");
  
  refreshTimeSeries(yesterdayDate);
  
  var source = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = source.getSheets()[0];
  
  var file = SpreadsheetApp.create(yesterdayDate);
  var file_ = DriveApp.getFileById(file.getId());
  var folder = DriveApp.getFolderById("ID_OF_MY_FOLDER"); 
  folder.addFile(file_);

  var destination = SpreadsheetApp.openById(file.getId());
  sheet.copyTo(destination).setName("Sheet1"); 
  destination.deleteSheet(destination.getSheets()[0]);
  
}

function subDaysFromDate(date,d){
  // date = start date
  // d = number of day to substract
  var result = new Date(date.getTime()-d*(24*3600*1000));
  return result
}
```

Cheers
