### ISSUE TITLE
TypeError: Cannot call method "getContentText" of undefined.

### ISSUE THREAD

**Issue by Rakeshmadhira** [simonbromberg/googlefitbit#3]
Hi, 
 I have done the same that you mentioned in the readme when i hit sync i am getting this error .
Can you please help me out on this ?

TypeError: Cannot call method "getContentText" of undefined.

Sheet last synced: Thu Sep 17 2015 16:44:13 GMT-0700 (PDT)  
Battery 
Last Sync  
Date

**Comment by simonbromberg** [comment]
Check the logs in the script editor
