### ISSUE TITLE
Can't get Intraday data

### ISSUE THREAD

**Issue by JJlily** [simonbromberg/googlefitbit#33]
I have followed all the instructions and managed to get interday data to work. I'm trying to go through and apply the same steps to the intraday scripts - I've tired both. The issue I'm having is that I can't get the 'Sync' option to show up for the last steps. I have no idea where I'm going wrong but noticed on these script there is no mention of sync function. 

Hope you can help, thanks!

**Comment by simonbromberg** [comment]
Closing because insufficient information and almost a year old.
