### ISSUE TITLE
Error: Access not granted or expired

### ISSUE THREAD

**Issue by effectively0** [simonbromberg/googlefitbit#34]
I've followed the instructions in Interday.gs without any issues, however when syncing at the end of the instructions, the error in Google spreadsheets comes up in a red box: "**Error: Access not granted or expired. Details Dismiss**".
Clicking 'Details' returns the message box "**Error: Access not granted or expired.**".
Clicking on the 'Fitbit' Menu and 'Authorize' brings up a side box on the right with a link which leads to '_fitbit.com/oauth2/authorize?client_id=...._' with the following error message:
"**The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.**

**Developer information: invalid_request - Invalid redirect_uri parameter value** "
I have the latest library resource 'OAuth2' available which is currently at version 26.

**Comment by simonbromberg** [comment]
Sounds like you may not have set everything up properly.

The Readme also suggests using version 19.

**Comment by effectively0** [comment]
Readme.md clearly states "_**Add the Oauth2...Select the latest version and click Save**_". Regardless, I have switched to Oauth2 v19 to try this and it still does not work. I checked the Client ID, Client Secret and Project ID to be sure, but these did not change upon switching Oauth2 v19 and still match the fitbit apps' registration.
Is anyone able to confirm if this still works for them? Any assistance would be greatly appreciated.

**Comment by effectively0** [comment]
Update: I had to go through the 'Authorize' menu in the Google Spreadsheets 'Fitbit' menu, open the link to the Fitbit webpage and authorize (all) the checkboxes. Script now works and is updating so it seems the OAth2 version was causing the error.
@simonbromberg might want to update that Readme.md to reflect that OAuth2 v19 is the working version, not the latest version?

**Comment by simonbromberg** [comment]
Already says right there:

> (Note: this library is in active development and newer versions may no longer work with the current version of the scripts in this repository — version 19 should work for now).
