### ISSUE TITLE
Code 401 error

### ISSUE THREAD

**Issue by secretdog** [simonbromberg/googlefitbit#4]
When sync ended, this error occurs.(interday)

https://api.fitbit.com/1/user/-/profile.json에 대한 요청이 실패하여 코드 401이(가) 반환되었습니다(Request failed. Code 401 returned). 서버 응답이 잘림: {"errors":[{"errorType":"authorization","fieldName":"authorization","message":"This application does not have permission to access profile data."}]...(전체 응답을 확인하려면 muteHttpExceptions 옵션을 사용하세요.)

**Comment by chrigublaser** [comment]
Hi secretdog

i had the same issue, you need to add profile scope to your request against fitbit

interday.js line 71
change from .setScope('activity') to .setScope('activity profile')

for more information visit https://dev.fitbit.com/docs/oauth2/?utm_campaign=website&utm_source=sendgrid.com&utm_medium=email#scope

regards
chrigu

**Comment by chrigublaser** [comment]
to get the whole interday.gs script running, you also need to add the settings scope

.setScope('activity profile settings')

**Comment by simonbromberg** [comment]
Looks like Fitbit changed their API a bit. Thank you chrigu83. Will update the scripts accordingly.

Note if you have an existing script and you change the scope, you will need to reset and re-authorize.

**Comment by secretdog** [comment]
Thank you!
