### ISSUE TITLE
Data downloading error.

### ISSUE THREAD

**Issue by secretdog** [simonbromberg/googlefitbit#5]
This errors occurs.

Error downloading foods/log/caloriesIn
Error downloading sleep/timeInBed
Error downloading sleep/minutesAsleep
Error downloading sleep/minutesAwake
Error downloading sleep/awakeningsCount
Error downloading body/weight
Error downloading body/bmi
Error downloading body/fat

and result is this.
![2015-10-22 11 57 39](https://cloud.githubusercontent.com/assets/1772554/10656185/2ba500c2-78b7-11e5-8867-ffe64df6b2c2.png)

**Comment by simonbromberg** [comment]
It's unclear what you're asking, and the script in the repo doesn't support those parts of the Fitbit API, and based on the screenshot it looks like your data downloaded fine.
