### ISSUE TITLE
Additional information regarding Sync errors on some Fitbit data

### ISSUE THREAD

**Issue by djjstew** [simonbromberg/googlefitbit#7]
These are the Loggables that are having issues:
foods/log/claoriesIn
sleep/timeInBed
sleep/minutesAsleep
sleep/minutesAwake
sleep/awakeningsCount
body/weight
body/bmi
body/fat

I noticed that all the Loggables with activities/log work and foods,sleep and body do not.  Sorry I am not experienced enough to figure out why and how to fix the Logger.log function or maybe a better way to define the var.  So I edited the var LOGGABLES section to remove those that are not working , add floors and put the activities in the order you would see them if you did a direct download from Fitbit.

// Default loggable resources (from Fitbit API docs).
var LOGGABLES = ["activities/log/calories", "activities/log/steps", "activities/log/distance","activities/log/floors","activities/log/minutesSedentary","activities/log/minutesLightlyActive","activities/log/minutesFairlyActive","activities/log/minutesVeryActive","activities/log/activityCalories",];

**Comment by donaldrnoble** [comment]
Simon, firstly thanks for making this script available, it is very helpful. 

I am not much of a coder, so can't offer any modifications to the script, but some observations below in case you ever decide to update this script in future.

I seem to be having a similar problem to djjstew, and noticed that where your script cannot get the data, it appears to duplicate the previous column. I therefore have 2 identical columns for Calories - the second one presumably being in place of CaloriesIn. I then have 8 columns for MinutesVeryActive, 
accounting for the 4 sleep and 3 body fields.

I do not use FitBit to log calories in, sleep or body weight, so this may be causing your script to fail if no data is returned from the API. It is not a major issue, I can just delete the duplicate columns. I thought I would just note this issue for your reference.

**Comment by djjstew** [comment]
donaldrnoble I am not a coder either but was able to notice where the issues were located in the code.  It is very easy fix as simple as a copy and paste.  At the bottom of my post above you can copy that code into the section of the script in your spreadsheet.  You can find that about 1/4 way down.  I run the script about once a week and it is much easier than doing the download from Fitbit and merging data.  Let me know if you have any questions.
