### ISSUE TITLE
ScriptProperties is deprecated

### ISSUE THREAD

**Issue by ActuarialChef** [simonbromberg/googlefitbit#9]
Hi Simon

I opened an issue a little bit ago which I thought was resolved by using the correct script. However, I found that the interday script uses ScriptProperties, which is deprecated and not working. I modified the script to use PropertiesService - I'm have a somewhat limited understanding of coding, but I modified each function which included "ScriptProperties.setProperty" or "ScriptProperties.getProperty" by doing the following:
1. Add `var userProperties = PropertiesService.getUserProperties();` as the first line of the function
2. Replace all instances of `ScriptProperties.setProperty` with `userProperties.setProperty`
3. Replace all instances of `ScriptProperties.getProperty` with `userProperties.getProperty`

I _think_ that adding `var userProperties = PropertiesService.getUserProperties();` anywhere before line 44 would have also worked instead of adding it as the first line of any function using ScriptProperties, but I didn't test this.

**Comment by simonbromberg** [comment]
Will take a look

**Comment by simonbromberg** [comment]
Started from scratch with interday.gs, but the script as is worked fine for me. When something is "Deprecated" it doesn't mean it is no longer usable, it just means they no longer support it and it may eventually be removed. Should still replace the deprecated items, but I don't know if this is what caused your issue. (Although I have seen that sometimes Google Scripts behave inconsistently.)
